site_name: Jithin BP
site_url: https://jithinbp.in


theme:
  name: 'material'
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: images/kuttypy.png
  favicon: 'images/kuttypy.png'
  features:
    - navigation.footer
    - content.code.copy
  icon:
    annotation: material/arrow-right-circle 
 
docs_dir: .
site_dir: ../site
use_directory_urls: false

#theme: 'readthedocs'
markdown_extensions:
    - toc:
        permalink: True
    - admonition
    - smarty
    - attr_list
    - wikilinks
    - codehilite:
        linenums: False
    - pymdownx.arithmatex
    - pymdownx.snippets
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences:
       preserve_tabs: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: True
    - pymdownx.tilde


extra_css: ["assets/main.css","assets/lightbox/css/lightbox.min.css","assets/carousel.css","assets/xtra.css"]
extra_javascript: ["assets/lightbox/js/lightbox-plus-jquery.min.js", "assets/carousel.js"]

site_favicon: 'images/favicon.ico'

extra:
  palette:
      primary: '#087da1'
      accent: '#00a889'
  generator: false
  social:
    - icon: fontawesome/brands/twitter 
      link: https://x.com/jithinbp_
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/jithin_bp
    - icon: fontawesome/brands/github
      link: https://github.com/jithinbp


plugins:
   - search
   - same-dir
   - exclude-search:
      exclude:
        - workshopnano.md
        - boards.md
   - table-reader
   #- page-to-pdf


repo_name: 'jithinbp/jithinbp.github.io'
repo_url: 'https://github.com/jithinbp/jithinbp.github.io'
copyright: 'Copyright © 2019 <a href="https://jithinbp.in">JITHIN BP</a>'

nav:
    - Home: 'index.md'
    - Environment Sensors: pages/environment.html
    - MQTT: mqtt.md
    - QUIZ Server: quiz_server.md
    - Kuttypy Nano: workshopnano.md
    - CAEN on Ubuntu: CAEN.md
    - Getting Started:
        - 'Boards': 'boards.md'

    - Projects:
        - 'Wedding': pages/wedding.html

    - Home:
        - Curriculum Vitae: curriculum-vitae.md
    - Masters Research:
        - Masters Thesis Full Text: ms-thesis-full-text.md
        - Thin Film Deposition: thin-film-deposition-at-iiser-mohali.md
        - PCAR Spectroscopy: pcar-spectroscopy.md
        - Scanning Tunneling Microscopy: scanning-tunneling-microscopy.md
        - Liquid Helium Cryostat: liquid-helium-cryostat.md
        - MFP-3D Atomic Force Microscope: mfp-3d-atomic-force-microscope.md
        - Probes for Cryostats: probes-for-cryostats.md
        - Other PLD Attempts: na2iro3-depositionimaging.md
        - Next Door Neighbours: the-refrigerator-next-door.md
    - Academic Projects:
        - Archaeology and Android: applications-of-mobile-technology-in-archaeology.md
        - Radiation Detection and Analysis: multi-channel-analyzer-for-radiation-analysis.md
        - Software PID Controller: software-pid-controller.md
        - Optics Lab:
            - Pendulum Tracking with OpenCV: pendulum-tracking-with-opencv.md
            - Beam Profile Extraction with OpenCV: beam-profile-extraction-with-opencv.md
            - Spatial Light Modulation with a Dismantled Projector: spatial-light-modulation-with-a-dismantled-projector.md
        - Virtual Lab Project: virtual-lab-project.md
        - 3D Phase Portrait Simulations: 3d-phase-portaits.md
        - Ideal Gas Mixing Simulation: ideal-gas-mixing-simulation.md
    - A Versatile Labtool:
        - Home Page: a-versatile-labtool.md
        - Getting Started: a-versatile-labtool/getting-started.md
        - Calibration:
            - Calibration and Accuracy: vlabtool/calibrating-the-analog-bits-for-maximum-accuracy.md
            - Calibrating DAC Channels: vlabtool/calibrating-dac-channels.md
        - Design and Construction:
            - System Diagram: vlabtool/system-diagram.md
            - Artists Impression: vlabtool/artists-impression.md
            - 3D printing Enclosure: vlabtool/3d-printing-enclosure.md
            - I2C Bus 3.5mm Jack: vlabtool/i2c-3-jack.md
            - Bill of Materials: vlabtool/bom.md
            - Waveform Generators: 
                - 28 bit DDS: vlabtool/28bitdds.md
                - 15kHz Sine Wave: vlabtool/sinewavegen.md
            - Docs and interactive help: vlabtool/help.md
            - Wireless Subunits: vlabtool/wireless-subunits.md
            - Alternate Interfaces:
                - Standalone OLED: vlabtool/oled.md
                - ESP8266 WiFi: vlabtool/esp8266.md
                - Raspberry Pi: vlabtool/rpi.md
                - Android App: vlabtool/android.md
            - 24 Bit ADC Add On Board : vlabtool/addon24bit.md
            - Addressable RGB LEDs: vlabtool/ws2812.md
            - Doppler Radar: vlabtool/hb100.md
            - Purchase: vlabtool/purchase.md
    - Vlabtool-V2:
        - Home Page: vlabtoolv2/home.md
        - First Prototype: vlabtoolv2/proto.md
        - Sensors and Add-ons:
            - Inductance based linear encoder: vlabtoolv2/linear_encoder.md
            - Position sensing TCD2648AP: vlabtoolv2/tcd3648.md
            - External Sensors: vlabtoolv2/sensors.md
            - Testing various sensors: vlabtoolv2/sensors2.md
            - High Resolution Add-ons: vlabtoolv2/highresaddons.md
        - Construction:
            - Prototypes 2 and 3: vlabtoolv2/proto2and3.md
            - Larger form factor: vlabtoolv2/larger.md
            - Laser Cut Enclosures: vlabtoolv2/lasercut.md
        - Wireless Subunits: vlabtoolv2/wireless.md
        - More Features:
            - Amplitude Modulations AD633: vlabtoolv2/ampmod.md
            - Bandpass filter: vlabtoolv2/bodeplots.md
            - Calibrating calibrator: vlabtoolv2/keithley.md
            - 125ksps streaming: vlabtoolv2/streaming.md
    - Hobby Projects:
        - POV Display: pov.md
        - Web based graphical coding: graphicalcoding.md
        - ExpEYES android and webapp: expeyeswebapp.md
        - Miscellaneous Hobby Projects: misc.md
    - Github:
        - PCAR Spectroscopy: pcar.md


